# Generated by Django 3.0.7 on 2020-07-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status post', 'verbose_name_plural': 'status post'},
        ),
    ]
